### ISSUE TITLE
Make event date selection better

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#10]
It sucks now. Just use common sense.

**Comment by jalbertbowden** [comment]
what is the event date selection? looking at
http://www.startupwichita.com/events
its not clear to me what is desired.

**Comment by kentonh** [comment]
@jalbertbowden at events/new the date selection is just dropdowns for month, date, hour, minute. It would be better with a date picker, and I think setting the default time to the current hour.

![screenshot 2016-09-27 15 01 34](https://cloud.githubusercontent.com/assets/868295/18889646/7b952d82-84c3-11e6-9f14-6f5cd8519a0e.png)

**Comment by jalbertbowden** [comment]
ok, i signed up, i see it now.
going to go with native html5 input type="date" and lets see what happens

**Comment by kentonh** [comment]
Closed by @jarrettgreen with #51
