### ISSUE TITLE
'claim_people_path' not written

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#4]
This action should let a user claim a Person record if it is not connected to a User.

The goal is to let Users add a Person without requiring that human to be signed up, then let the human claim the Person profile later.

**Comment by kentonh** [comment]
Taking the importance of the goal, I think the proper method would be to email an admin with that person's email address, and have them send a selfie with a hand-written note with some specific verification information. (What do you love about Wichita? etc.)

It would be a manual process of verification from Admin's but I think it would work.

**Comment by rangerchaz** [comment]
We could tie in some social networking accounts as well. If we know their Facebook or Twitter account, we can use a login dialog to verify them. We could also do a simple email verification. Thoughts?

**Comment by kentonh** [comment]
We need to have non-public information to verify with, but whatever that is I'm for it.

**Comment by kentonh** [comment]
Not really a thing anymore
