### ISSUE TITLE
Event scraping from certain places

### ISSUE THREAD

**Issue by sethetter** [StartupWichita/startupwichita.com#40]
Pulling in events automatically from Meetup or FB for relevant groups would be great.

**Comment by kentonh** [comment]
Christian has done this...

**Comment by sethetter** [comment]
In PHP :) and only for Facebook. I'm planning to do the meetup integration
on Wichitawesome, so I can do this one too, but yeah.

**Comment by kentonh** [comment]
@sethetter are you going to do this for Hacktoberfest?

**Comment by sethetter** [comment]
@kentonh I suppose I could :)

**Comment by sethetter** [comment]
The world of Ruby libs for accessing the Meetup API has grown dark and dismal it seems.

**Comment by sethetter** [comment]
Meetup portion done in 79bc876

**Comment by kentonh** [comment]
Maybe we just do Facebook events for certain pages
1. 1 Million Cups
2. Labor Party
3. Groundworks

**Comment by kentonh** [comment]
It appears the recurring events that pull from meetup.com has some... issues. If you look at the event's page, at the end of the page there are a list of events that are from the past. Those are all visible because they were created with long term end dates (Once was scheduled to be over 5-15-4692)

**Comment by sethetter** [comment]
@kentonh fixed in 6f31618

**Comment by kentonh** [comment]
This is good enough
