### ISSUE TITLE
People index is littered with half completed profiles

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#43]
Need a way to deal with this.

Ideas are showing names in a list only (if there is no description provided)

Monthly email reminding people to keep their profile updated and/or hide the profile from the index if they are no longer part of the community.

**Comment by ChanChar** [comment]
@kentonh I can take this one :].

The easy change is to filter out those profiles with partial data (eg. missing description).

How do you feel about ordering profiles based on profile completeness? For example, the more information you provide, the higher you are within the list? We can also incorporate this with the previous idea and have a lower limit that requires at least your name and description to be put on the list.

**Comment by kentonh** [comment]
@ChanChar I like that ordering idea. It would be good to check on the avatar image as well, but I'm not sure that we can with an affirmative Gravatar response.

**Comment by ChanChar** [comment]
@kentonh PR is up. avatar images can be checked by checking to see if a file name was set. Didn't add the lower limit yet as I know the scoring should be tweaked based on mod input.
