### ISSUE TITLE
@Mentions 

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#49]
In a News or Event record, I want to be able to use the "@" symbol and the URL slug of a Person to link to their Person Record detail.

Same for a Company and Resource

**Comment by rlgreen91** [comment]
Can you provide a bit more detail on what exactly the relationship should be between a News instance and a Person instance?  For example, should each News instance belong to a Person instance, or should it have at least one author, who is a person or company?

Additionally, what exactly are the parameters of the task?  Implementing this relationship for both News and Event models?  Just News in one PR and Event in another?

**Comment by kentonh** [comment]
Hey @rlgreen91,

I'm just looking for a News or Event instance to link to a Person resource when that person is "mentioned" which would be an "@" followed by the Person url slug (which we should have in the Person record already)

So in the description text of the Event record for my birthday, I could say `happy birthday, @kenton-hansen` and it would link to my Person at http://startupwichita.com/profile/kenton-hansen
