### ISSUE TITLE
Add error messages in signup page

### ISSUE THREAD

**Issue by dreamingblackcat** [StartupWichita/startupwichita.com#56]
There is no feedback on sign up page if something went wrong. Wouldn't it be better to show error messages (at least the default devise messages) when something went wrong?

**Comment by BhaveshSGupta** [comment]
Hey, I guess on signup page all the fields should be required, I suggest we should add the required validator.  I can take up this issue as a part of my hacktoberfest

**Comment by kentonh** [comment]
It's yours

**Comment by AustinMCrane** [comment]
fixed in pull request #77
