### ISSUE TITLE
Fix opengraph image for social

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#65]
Right now anytime anyone posts anything to Facebook, my face shows up. That's nice and all, but I'd prefer something like our logo be used.

By default use the svg logo of the site available here: 
![sw_logo_dark](https://user-images.githubusercontent.com/868295/30828076-fe24bcd4-a201-11e7-8eb6-23f9b284bfee.png)
![sw_mark_dark](https://user-images.githubusercontent.com/868295/30828075-fe207b7e-a201-11e7-9bf9-44857ee93da5.png)

Issue #86 would add the ability to use the Social Graph image of the article or event that is being reposted. That may be a better option.

**Comment by BhaveshSGupta** [comment]
Hi, The minimum image size for og: image should be 200*200, please refer to this https://developers.facebook.com/docs/sharing/best-practices, 
![ogimage](https://cloud.githubusercontent.com/assets/4209637/19288939/06d1ce38-9026-11e6-81a5-257ae7d6fb34.jpg)

I guess we can update the current image to minimum size, I can take this up

**Comment by kentonh** [comment]
Thanks, @BhaveshSGupta A better logo file is: https://www.dropbox.com/s/tjk7967cfed91b9/SW_Logo_Dark.png?dl=0

**Comment by BhaveshSGupta** [comment]
I am making it to 200*200, where should i make the PR to into which branch ? can you help me in  making these changes thanks

**Comment by kentonh** [comment]
PR into the Master branch, thanks

**Comment by AustinMCrane** [comment]
I got this

**Comment by kentonh** [comment]
No one is working on this

**Comment by BhaveshSGupta** [comment]
I remember I was not able to find the place to replace the image and run the project locally 
 I think image needs to be replaced in this two file https://github.com/StartupWichita/startupwichita.com/blob/13108a967ba7271896213ee4e07359aa8681fa1b/app/assets/images/StartupwichitaCom.html#L20 https://github.com/StartupWichita/startupwichita.com/blob/6b8529ea281bff3c6fcc26f7b5de2e686cc5f2d1/app/views/layouts/application.html.erb#L20

and Still trying to figure out how to run this locally

**Comment by kentonh** [comment]
@BhaveshSGupta no problem. I'm just setting up this issue for this year's Hacktoberfest

**Comment by lafentres** [comment]
@kentonh , I could fix this. I noticed a couple of other issues when I was looking at this as well. 

1. The meta tags don't dynamically pull in the request url, so any share from any page (like /events for example), will always point back to the homepage. 
2. Not a huge issue really, but the title for the share doesn't change. 

I could fix these as well and any other sharing things I notice.

**Comment by kentonh** [comment]
@lafentres that'd be awesome! Thanks.
