### ISSUE TITLE
people index page is slow

### ISSUE THREAD

**Issue by AustinMCrane** [StartupWichita/startupwichita.com#85]
The people index page is super slow for initial loading.

**Comment by ksolo** [comment]
@kentonh @AustinMCrane 
I'll take a quick look at this tonight/tomorrow and open up a PR soon.

**Comment by ksolo** [comment]
@AustinMCrane @kentonh 
The person index page has a (5xN) + 1 query going on. I have it down to N + 1, but the ActsAsTaggableOn is the only one remaining that I'm not sure how to eliminate just yet.
