### ISSUE TITLE
Remove certain users from People page

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#88]
Change the way that people are show on the People page.

The People index view should only use the current template for accounts who satisfy the following requirements:

Have completed their profiles, a complete profile would include:

1. First and last name
1. contact email
1. Company name
1. avatar with Gravatar or uploading a file
1. at least 60 characters in their bio *OR* three News or Event posts

**All other People should have a simplified template, showing just their first name, last name**

**Comment by yoonwaiyan** [comment]
Hi, can I help out with this issue? If yes, would like to know what's the criteria of completing the profile i.e. first name and last name as in validation or completed all fields in edit profile page? What's the details about "company if those exist"? And do we still include the "inactive person" in filtering?

**Comment by kentonh** [comment]
@yoonwaiyan I'd love your help.

I'm editing the issue with more detail to answer your questions and clarify further.

**Comment by yoonwaiyan** [comment]
Alright, will work on this.

**Comment by sa77** [comment]
@kentonh is this issue resolved ?

**Comment by kentonh** [comment]
@sa77 it looks like @yoonwaiyan is working on this issue.
