### ISSUE TITLE
Make Posts (events, news) and Mentions count towards a User's Score

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#89]
Users are ordered by default on the People page by how complete their profile is. Need to add the number of posts a user has contributed as well as the number of posts that mention them to the scores.

**Comment by AfroDevGirl** [comment]
@kentonh Hey! I'll pick up this issue, quick question. Any preference on the level of scoring for posts and mentions? Seems like it should be high ranking but the current scoring is a little scattered as a newcomer to the project. Thanks in advance for your help!

**Comment by kentonh** [comment]
Thanks, @AfroDevGirl!

Just adding it to the array of scoring on `/models/person.rb` we'll end up tweaking the points-per-post and points-per-mention as we go along to make things fair.

**Comment by kentonh** [comment]
Fixed with #99
