### ISSUE TITLE
Make better contribution docs

### ISSUE THREAD

**Issue by kentonh** [StartupWichita/startupwichita.com#94]
Currently, it's not intuitive on how to get a local version up a running, and how we prefer PRs. Really, we don't have a way that we want them.

**Comment by Jedeu** [comment]
Hey @kentonh would love to help with this issue, though I guess we should discuss about the preferred way/guidelines to submit PRs and to spin up a local?

**Comment by kentonh** [comment]
I like what Jekyll has done with https://jekyllrb.com/docs/contributing/

That could be added to the readme

**Comment by gagaception** [comment]
Hi @kentonh, just pushed pull request for this issue. I hope this is what you wanted

**Comment by kentonh** [comment]
closed with #103
